export const ROUTE_NAMES = {
  // MAIN STACK SCREENS
  courseSearch: 'CourseSearch',
  testSearch: 'TestSearch',
  taskSearch: 'TaskSearch',
  filter: 'Filter',
  selectCategory: 'SelectCategory',
  reviews: 'Reviews',
  courseLeaveReview: 'CourseLeaveReview',
  courseFinish: 'CourseFinish',
  payment: 'Payment',
  splashStack: 'SplashStack',
  lesson: 'Lesson',
  myLesson: 'MyLesson',
  testPreview: 'TestPreview',
  testPass: 'TestPass',
  myTestPass: 'MyTestPass',
  testResult: 'TestResult',
  myTestResult: 'MyTestResult',
  testCompleted: 'TestCompleted',
  courseTask: 'CourseTask',
  bottomTab: 'BottomTab',
  // SPLASH STACK SCREENS
  splash: 'Splash',
  language: 'Language',
  // BOTTOM BAR SCREENS
  coursesStack: 'CoursesStack',
  testsStack: 'TestsStack',
  myCoursesStack: 'MyCoursesStack',
  tasksStack: 'TasksStack',
  menuStack: 'MenuStack',
  // TABS
  // Courses
  courses: 'Courses',
  courseDetail: 'CourseDetail',
  // Tests
  tests: 'Tests',
  testDetail: 'TestDetail',
  // My Courses
  myCourses: 'MyCourses',
  myTests: 'MyTests',
  myTasks: 'MyTasks',
  myCourseDetail: 'MyCourseDetail',
  testsTopBar: 'TestsTopBar',
  myCoursesTopBar: 'MyCoursesTopBar',
  myTestDetail: 'MyTestDetail',
  // Tasks
  tasks: 'Tasks',
  taskDetail: 'TaskDetail',
  // Menu
  menu: 'Menu',
  rating: 'Rating',
  refProgram: 'RefProgram',
  privacyPolicy: 'PrivacyPolicy',
  aboutService: 'AboutService',
  profile: 'Profile',
  //Auth
  login: 'Login',
  recovery: 'Recovery',
  register: 'Register',
  //News
  news: 'News',
  newsDetail: 'NewsDetail',
  history: 'History',
  changePassword: 'ChangePassword',
  profileEdit: 'ProfileEdit',
  //Schedule
  scheduleNavigator: 'ScheduleNavigator',
  scheduleLessons: 'ScheduleLessons',
  scheduleVisitis: 'ScheduleVisits',
  settings: 'Settings',
  operation: 'Operation',
  kaspiBank: 'KaspiBank',
  webViewer: 'WebViewer',
  //Journal
  journalNavigator: 'JournalNavigator',
  journals: 'Journals',
  myJournlas: 'MyJournals',
  readJournal:'ReadJournal',
  ubt: "UBT",
  selectSubjects: "SelectSubjects",
  ubtTest: "UBTTest",
  ubtCompleted: "UBTCompleted",
  ubtResult: "UBTResult",
};
